services:
  grampsweb-test:
    image: ghcr.io/gramps-project/grampsweb:26.7.0
    ports:
      - "5000"
    environment:
      GRAMPSWEB_TREE: testdb
      GRAMPSWEB_SECRET_KEY: integration-test-secret
